[package]
name = "Yakei"
version = "0.3.3"
edition = "2021"

[dependencies]
image = "0.24.6"
glob = "0.3.1"
imageproc = "0.23.0"
infer = "0.13.0"
num = "0.4.0"
clap = { version = "4.2.0", features = ["derive"] }
